# Локаторы
xpath:
  LOCATOR_LOGIN_FIELD: '//*[@id="login"]/div[1]/label/input'
  LOCATOR_PASS_FIELD: '//*[@id="login"]/div[2]/label/input'
  LOCATOR_ABOUT_LINK: '//*[@id="app"]/main/nav/ul/li[1]/a'
  LOCATOR_ABOUT_HEADER: '//*[@id="app"]/main/div/div/h1'


# Учетные данные для авторизации
login: WolverineLogan
password: 6972c9498c
